version: '2.1'
services:
  postgres:
    image: centos/postgresql-95-centos7
    ports:
      - '5432:5432'
    environment:
      - STAGE
    env_file:
      - ./.env.$STAGE.local
    volumes:
    - ./:/app
  app:
    environment:
      - STAGE
    env_file:
      - ./.env.$STAGE.local
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - ./:/app
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    entrypoint: ["./bin/docker/wait-for-postgres.sh", "./bin/docker/start-app.sh"]
