version: '2.1'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - STAGE
    env_file:
      - ./.env.$STAGE.local
  app:
    environment:
      - STAGE
    env_file:
      - ./.env.$STAGE.local
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - ./:/app
    ports:
      - '3000:3000'
    entrypoint: sh ./bin/docker/start-app.sh
