default: &default
  adapter: postgresql
  pool: 15
  timeout: 5000
  encoding: utf8

<%= Rails.env %>:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_DATABASE'] %>